name = "MarineEcosystemsJuliaCon2021"
uuid = "ae04bbf0-2c70-42d7-94da-2eb8e09f5880"
authors = ["gaelforget <gforget@mit.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
